extends Camera2D

func _ready() -> void:
	$"../../Map 1/Chunks/Chunk Grass/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass2/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass3/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass4/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass5/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass6/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass7/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass8/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass9/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass10/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass11/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass12/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass13/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass14/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass15/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass16/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass17/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass18/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass19/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass20/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass21/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass22/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass23/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass24/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass25/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass26/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass27/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass28/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass29/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass30/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass31/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass32/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass33/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass34/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass35/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass36/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass37/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass38/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass39/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass40/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass41/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass42/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass43/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass44/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass45/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass46/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass47/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass48/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass49/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass50/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass51/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass52/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass53/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass54/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass55/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass56/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass57/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass58/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass59/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass60/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass61/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass62/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass63/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass64/Area2D".hide()

	$"../../Map 1/Cave/Cave Chunks/Cave Chunk/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk2/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk3/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk4/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk5/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk6/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk7/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk8/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk9/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk10/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk11/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk12/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk13/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk14/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk15/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk16/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk17/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk18/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk19/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk20/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk21/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk22/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk23/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk24/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk25/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk26/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk27/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk28/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk29/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk30/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk31/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk32/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk33/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk34/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk35/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk36/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk37/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk38/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk39/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk40/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk57/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk58/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk59/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk60/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk61/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk62/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk63/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk64/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk41/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk42/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk43/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk44/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk45/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk46/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk47/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk48/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk49/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk50/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk51/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk52/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk53/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk54/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk55/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk56/Area2D".hide()
	
func _on_area_2d_area_entered(area: Area2D) -> void:
	$"../../Map 1/Chunks/Chunk Grass/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass2/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass3/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass4/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass5/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass6/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass7/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass8/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass9/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass10/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass11/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass12/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass13/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass14/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass15/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass16/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass17/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass18/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass19/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass20/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass21/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass22/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass23/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass24/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass25/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass26/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass27/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass28/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass29/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass30/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass31/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass32/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass33/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass34/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass35/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass36/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass37/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass38/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass39/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass40/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass41/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass42/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass43/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass44/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass45/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass46/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass47/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass48/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass49/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass50/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass51/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass52/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass53/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass54/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass55/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass56/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass57/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass58/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass59/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass60/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass61/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass62/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass63/Area2D".show()
	$"../../Map 1/Chunks/Chunk Grass64/Area2D".show()
	
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk2/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk3/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk4/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk5/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk6/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk7/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk8/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk9/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk10/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk11/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk12/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk13/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk14/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk15/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk16/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk17/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk18/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk19/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk20/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk21/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk22/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk23/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk24/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk25/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk26/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk27/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk28/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk29/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk30/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk31/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk32/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk33/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk34/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk35/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk36/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk37/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk38/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk39/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk40/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk57/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk58/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk59/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk60/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk61/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk62/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk63/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk64/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk41/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk42/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk43/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk44/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk45/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk46/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk47/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk48/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk49/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk50/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk51/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk52/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk53/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk54/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk55/Area2D".show()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk56/Area2D".show()

func _on_area_2d_area_exited(area: Area2D) -> void:
	$"../../Map 1/Chunks/Chunk Grass/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass2/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass3/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass4/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass5/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass6/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass7/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass8/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass9/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass10/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass11/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass12/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass13/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass14/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass15/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass16/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass17/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass18/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass19/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass20/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass21/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass22/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass23/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass24/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass25/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass26/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass27/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass28/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass29/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass30/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass31/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass32/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass33/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass34/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass35/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass36/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass37/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass38/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass39/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass40/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass41/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass42/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass43/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass44/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass45/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass46/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass47/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass48/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass49/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass50/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass51/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass52/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass53/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass54/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass55/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass56/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass57/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass58/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass59/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass60/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass61/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass62/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass63/Area2D".hide()
	$"../../Map 1/Chunks/Chunk Grass64/Area2D".hide()

	$"../../Map 1/Cave/Cave Chunks/Cave Chunk/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk2/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk3/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk4/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk5/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk6/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk7/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk8/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk9/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk10/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk11/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk12/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk13/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk14/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk15/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk16/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk17/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk18/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk19/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk20/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk21/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk22/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk23/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk24/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk25/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk26/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk27/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk28/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk29/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk30/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk31/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk32/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk33/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk34/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk35/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk36/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk37/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk38/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk39/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk40/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk57/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk58/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk59/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk60/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk61/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk62/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk63/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk64/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk41/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk42/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk43/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk44/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk45/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk46/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk47/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk48/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk49/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk50/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk51/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk52/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk53/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk54/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk55/Area2D".hide()
	$"../../Map 1/Cave/Cave Chunks/Cave Chunk56/Area2D".hide()
